name: GitHub Secrets & Variables
run-name: ${{ github.actor }} is testing out GitHub Secrets & variables ğŸ¤«ğŸ”
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out variables & secrets
        run: |
            echo "the variable name is: ${{ vars.NAME }}"
            echo "the secret her name is: ${{ secrets.HER_NAME }}"
    
